# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode8.3

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ehby0IqEDAa0V6U7m7jGF6Rvb8bf8M+3ckwMsgE4WFqdTgnycOIlzPWsUb6Am95+/Ek1dEznzBLJ++th02VtOt4yfUwCpwjn0ddR7TSV/gmVrrgGy+sT29cTY2+zlPl3xoGffINHkN089GX/aA6viqZYxFCJT3fIwpaymZ15HGFjv3DUHat17sxajY+dkhDnvc8214Inicc9VHSBvJn07x2gU75WIG5047Ue8D4gNRsOWoI94hXl6IFcAnFzUz/m0sNb+gdo2UrY1+qsaqACIOinRVschCMAC5tN6uHDIXDyhkVuO+bYPoo7ieycmNB7sbTkwKTPbuG0cwTXvCzH5rM7mP8HWQ+MDV5HCWSTBowP4gnXY4d7D0dd/mRG8KZ5gHC2oQwx9a+w153z/g6JJWY23YXyCKS2x3vkeGuw/Ne9V77B8zOGS+qoYymsdg54//nHmoafGWz1WCMVgEXxpg3n16W5XRQ0tk0UNW43K8DIxF1BsJgl+WBcVFuvrdr4ER6DkVEZZbjVGrIeQw8m3fQXUyoH1WNxVmSfAyv9bxKcgkntSnMyJoYcUK6LcQtgJCS+PL4qtD08wVxiIeovekGqvM6oWP2BFDyxfwAnRpAA5/NpRKP6WWroASZdqy+1AT+paipzvEoi03rrxlY1xSVrdJPHw7zj/hbK2c5tw5I="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # hack: download legacy OSX 10.9 sdk from github
    - |
      echo "Installing MacOSX10.9.sdk"
      SDK_MD5="de552e9a4ef12999d2e1f25acce51a76"
      SDK_SHA256="a7e52651ec33f0fc7fc025734365854f012875748ebe1a5d1cd8555c5a118ebd"
      echo "Downloading SDK"
      SDK_NAME="MacOSX10.9.sdk"
      curl -OfsSL https://gist.github.com/viscid-hub/f108b33bcbe4bf7d1b63cf76de4d435a/raw/MacOSX10.9.sdk.tar.bz2
      echo "Decompressing SDK"
      bzip2 --decompress --force ${SDK_NAME}.tar.bz2
      echo "Verifying SDK"
      dl_md5="$(openssl dgst -md5 ${SDK_NAME}.tar | awk '{print tolower($NF)}')"
      dl_sha256="$(openssl dgst -sha256 ${SDK_NAME}.tar | awk '{print tolower($NF)}')"
      if [ "${SDK_MD5}" != "${dl_md5}" ]; then
        echo "!!!! MacOSX10.9.sdk md5 hash mismatch !!!!"
        echo "expected hash    : ${SDK_MD5}"
        echo "hash of download : ${dl_md5}"
        exit 1
      fi
      if [ "${SDK_SHA256}" != "${dl_sha256}" ]; then
        echo "!!!! MacOSX10.9.sdk sha256 hash mismatch !!!!"
        echo "expected hash    : ${SDK_SHA256}"
        echo "hash of download : ${dl_sha256}"
        exit 1
      fi
      echo "Extracting SDK"
      tar -xf MacOSX10.9.sdk.tar
      echo "Moving SDK"
      sdk_dest="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"
      sudo mkdir -p ${sdk_dest}
      sudo mv MacOSX10.9.sdk ${sdk_dest}/
      export CONDA_BUILD_SYSROOT="${sdk_dest}/MacOSX10.9.sdk"

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe viscid-hub --channel=main -m ./.ci_support/${CONFIG}.yaml
